workflows:
  android-workflow:
    name: Android Debug Build
    max_build_duration: 30
    environment:
      java: 17
      groups:
        - android_signing
      vars:
        PACKAGE_NAME: "com.lucknowmobiles.app"
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Generate Gradle Wrapper
        script: |
          gradle wrapper --gradle-version=8.0.2
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug -x lint --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
